<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Abhiram.Abstractions.Logging" Version="2.0.0" />
    <PackageVersion Include="Abhiram.Extensions.DotEnv" Version="1.1.1" />
    <PackageVersion Include="EntityFramework6.Npgsql" Version="6.4.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.23" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.12" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.19" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.19">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.19" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="xunit" Version="2.5.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>
</Project>